### ISSUE TITLE
Repo is missing a ted_app_meta_data.yml file

### ISSUE THREAD

**Issue by jhirbour** [tedconf/github_actions#1]
Please populate this repo with a [ted_app_meta_data.yml](https://github.com/tedconf/ted_app_meta_data/blob/master/samples/1.4/ted_app_meta_data.yml) file.

Also going forward new Repos should be created via terraform and not created via the Github UI.

**Comment by Leee-xx** [comment]
https://github.com/tedconf/github_actions/pull/2

**Comment by Leee-xx** [comment]
https://github.com/tedconf/github_actions/commit/20b9667e1b5dc7ec8bbe48b84dd2db5a54dbc632
